version: '3'

services:
  dev:
    build: .
    image: user-service:1.0
    container_name: user-service
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data:/var/lib/mysql