server:
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai
    username: root
    password: pass
  jpa:
    show-sql: true

  flyway:
      enabled: true
      out-of-order: true
      encoding: UTF-8
      url: jdbc:mysql://localhost:3306/
      schemas: user
      user: root
      password: pass


